---
- name: Provision EC2 instance with Docker, k3s, and deploy Flask app
  hosts: flask_server
  become: yes

  tasks:

    - name: Install Docker
      tags: install
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Enable Docker service
      tags: install
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Install k3s
      tags: k3s
      shell: |
        curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Wait for k3s to be ready
      tags: k3s
      shell: |
        until k3s kubectl get nodes; do sleep 5; done

    - name: Copy Kubernetes manifests clearly to the remote server
      tags: deploy
      copy:
        src: "../kubernetes/"
        dest: /tmp/
        mode: '0644'

    - name: Apply Kubernetes Deployment
      tags: deploy
      shell: k3s kubectl apply -f /tmp/flask-deployment.yml

    - name: Apply Kubernetes Service
      tags: deploy
      shell: k3s kubectl apply -f /tmp/flask-service.yml

    - name: Clean up manifest files
      tags: deploy
      file:
        path: "/tmp/{{ item }}"
        state: absent
      loop:
        - flask-deployment.yaml
        - flask-service.yaml

      