name: Ansible Provisioning and Kubernetes Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'ansible/**'
      - 'kubernetes/**'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::539247494423:role/GitHubActionsOIDCRole
          aws-region: us-east-1

      - name: Fetch EC2 Public IP from Terraform Cloud
        env:
          TFC_ORG: hello-k3s
          TFC_WORKSPACE: hello-k3s-ansible
          TFC_TOKEN: ${{ secrets.TF_API_TOKEN }}
        run: |
          run_id=$(curl -s \
            --header "Authorization: Bearer $TFC_TOKEN" \
            https://app.terraform.io/api/v2/organizations/$TFC_ORG/workspaces/$TFC_WORKSPACE/current-run | jq -r .data.id)

          output_url="https://app.terraform.io/api/v2/runs/$run_id/plan/output"

          echo "Waiting for Terraform output..."
          sleep 10

          ec2_ip=$(curl -s \
            --header "Authorization: Bearer $TFC_TOKEN" \
            $output_url | jq -r '.data.attributes.resource_changes[]? 
              | select(.type=="aws_instance") 
              | .change.after.public_ip')

          echo "Fetched EC2 IP: $ec2_ip"
          echo "::set-output name=ec2_ip::$ec2_ip"

      - name: Create dynamic inventory.ini
        run: |
          mkdir -p ansible
          echo "[flask_server]" > ansible/inventory.ini
          echo "${{ steps.deploy.outputs.ec2_ip }}" >> ansible/inventory.ini

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Wait for SSH to be Ready
        run: |
          ip="${{ steps.deploy.outputs.ec2_ip }}"
          echo "Waiting for SSH on $ip..."
          for i in {1..20}; do
            if ssh -o StrictHostKeyChecking=no ec2-user@$ip 'echo SSH is up'; then
              echo "SSH is ready!"
              break
            fi
            sleep 10
          done

      - name: Run Ansible Playbook
        working-directory: ansible
        run: ansible-playbook -i inventory.ini playbook.yml
