name: Terraform and Ansible Automation

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
      - 'ansible/**'
      - 'kubernetes/**'

jobs:
  terraform-cloud-apply:
    runs-on: ubuntu-latest
    env:
      TF_CLOUD_ORGANIZATION: hello-k3s
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      TF_WORKSPACE: hello-k3s-ansible

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform Cloud Init & Apply
        working-directory: terraform
        run: |
          terraform init
          terraform apply -auto-approve

  ansible-run:
    needs: terraform-cloud-apply
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Run Ansible Playbook
        working-directory: ansible
        run: |
          ansible-playbook -i inventory.ini playbook.yml
